services:
  - type: web
    name: shadow-game-shop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: APIFY_API_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
